require:
  - standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - bin/**/*
    - vendor/**/*

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/TimeZone:
  Enabled: false
