inherit_from:
  - ../.rubocop.yml

RSpec/ContextWording:
  Prefixes:
    - using
    - via
    - when
    - with
    - without

RSpec/DescribedClass:
  Enabled: true

RSpec/ExampleLength:
  Max: 15

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    TSearch: "tsearch"
    DMetaphone: "dmetaphone"

RSpec/MultipleExpectations:
  Max: 5
